

deck1 = [
    {
        "id": "549481",
        "name": "Prevent Rat",
        "desc": "This creature is shielded with a tough hide of hair and is excellent at defending itself.",
        "atk": "500",
        "def": "2000",
        "type": "Normal Monster",
        "level": "4",
        "race": "Beast",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/549481.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/549481.jpg"
    },
    {
        "id": "732302",
        "name": "Temple of Skulls",
        "desc": "A mysterious temple of skulls and bones that pulls in unsuspecting enemies.",
        "atk": "900",
        "def": "1300",
        "type": "Normal Monster",
        "level": "4",
        "race": "Zombie",
        "attribute": "DARK",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/732302.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/732302.jpg"
    },
    {
        "name": "Kojikocy",
        "desc": "A man-hunter with powerful arms that can crush boulders.",
        "atk": "1500",
        "def": "1200",
        "type": "Normal Monster",
        "level": "4",
        "race": "Warrior",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/1184620.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/1184620.jpg"
    },
    {
        "id": "1784619",
        "name": "Uraby",
        "desc": "Fast on its feet, this dinosaur rips enemies to shreds with its sharp claws.",
        "atk": "1500",
        "def": "800",
        "type": "Normal Monster",
        "level": "4",
        "race": "Dinosaur",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/1784619.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/1784619.jpg"
    },
    {
        "id": "2118022",
        "name": "Hyosube",
        "desc": "This amphibian is strong on the attack, but leaves much to be desired when defending.",
        "atk": "1500",
        "def": "900",
        "type": "Normal Monster",
        "level": "4",
        "race": "Aqua",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2118022.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2118022.jpg"
    },
    {
        "id": "5053103",
        "name": "Battle Ox",
        "desc": "A monster with tremendous power, it destroys enemies with a swing of its axe.",
        "atk": "1700",
        "def": "1000",
        "type": "Normal Monster",
        "level": "4",
        "race": "Beast-Warrior",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/5053103.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/5053103.jpg"
    },
    {
        "id": "5265750",
        "name": "Skull Mariner",
        "desc": "A pirate ship that appears out of the mist and sinks any seagoing vessels.",
        "atk": "1600",
        "def": "900",
        "type": "Normal Monster",
        "level": "4",
        "race": "Warrior",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/5265750.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/5265750.jpg"
    }
]

deck2 = [
    {
        "id": "2311603",
        "name": "Overdrive",
        "desc": "An all-terrain armored vehicle armed with a heavy-duty machine gun.",
        "atk": "1600",
        "def": "1500",
        "type": "Normal Monster",
        "level": "4",
        "race": "Machine",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2311603.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2311603.jpg"
    },
    {
        "id": "2483611",
        "name": "Water Omotics",
        "desc": "Transforms the water overflowing from a jar into attacking dragons.",
        "atk": "1400",
        "def": "1200",
        "type": "Normal Monster",
        "level": "4",
        "race": "Aqua",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2483611.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2483611.jpg"
    },
    {
        "id": "2863439",
        "name": "Fiend Reflection 2",
        "desc": "A bird-beast that summons reinforcements with a hand mirror.",
        "atk": "1100",
        "def": "1400",
        "type": "Normal Monster",
        "level": "4",
        "race": "Winged Beast",
        "attribute": "LIGHT",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2863439.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2863439.jpg"
    },
    {
        "id": "2906250",
        "name": "Grappler",
        "desc": "A devious snake with a thick body that wraps around an enemy monster and squeezes the life out of it.",
        "atk": "1300",
        "def": "1200",
        "type": "Normal Monster",
        "level": "4",
        "race": "Reptile",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2906250.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2906250.jpg"
    },
    {
        "id": "3134241",
        "name": "Flying Kamakiri 2",
        "desc": "A flying mantis that feeds primarily on insects.",
        "atk": "1500",
        "def": "800",
        "type": "Normal Monster",
        "level": "4",
        "race": "Insect",
        "attribute": "WIND",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/3134241.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/3134241.jpg"
    }
]



cards = [
    {
        "id": "549481",
        "name": "Prevent Rat",
        "desc": "This creature is shielded with a tough hide of hair and is excellent at defending itself.",
        "atk": "500",
        "def": "2000",
        "type": "Normal Monster",
        "level": "4",
        "race": "Beast",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/549481.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/549481.jpg"
    },
    {
        "id": "732302",
        "name": "Temple of Skulls",
        "desc": "A mysterious temple of skulls and bones that pulls in unsuspecting enemies.",
        "atk": "900",
        "def": "1300",
        "type": "Normal Monster",
        "level": "4",
        "race": "Zombie",
        "attribute": "DARK",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/732302.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/732302.jpg"
    },
    {
        "id": "1184620",
        "name": "Kojikocy",
        "desc": "A man-hunter with powerful arms that can crush boulders.",
        "atk": "1500",
        "def": "1200",
        "type": "Normal Monster",
        "level": "4",
        "race": "Warrior",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/1184620.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/1184620.jpg"
    },
    {
        "id": "1784619",
        "name": "Uraby",
        "desc": "Fast on its feet, this dinosaur rips enemies to shreds with its sharp claws.",
        "atk": "1500",
        "def": "800",
        "type": "Normal Monster",
        "level": "4",
        "race": "Dinosaur",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/1784619.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/1784619.jpg"
    },
    {
        "id": "2118022",
        "name": "Hyosube",
        "desc": "This amphibian is strong on the attack, but leaves much to be desired when defending.",
        "atk": "1500",
        "def": "900",
        "type": "Normal Monster",
        "level": "4",
        "race": "Aqua",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2118022.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2118022.jpg"
    },
    {
        "id": "2311603",
        "name": "Overdrive",
        "desc": "An all-terrain armored vehicle armed with a heavy-duty machine gun.",
        "atk": "1600",
        "def": "1500",
        "type": "Normal Monster",
        "level": "4",
        "race": "Machine",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2311603.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2311603.jpg"
    },
    {
        "id": "2483611",
        "name": "Water Omotics",
        "desc": "Transforms the water overflowing from a jar into attacking dragons.",
        "atk": "1400",
        "def": "1200",
        "type": "Normal Monster",
        "level": "4",
        "race": "Aqua",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2483611.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2483611.jpg"
    },
    {
        "id": "2863439",
        "name": "Fiend Reflection 2",
        "desc": "A bird-beast that summons reinforcements with a hand mirror.",
        "atk": "1100",
        "def": "1400",
        "type": "Normal Monster",
        "level": "4",
        "race": "Winged Beast",
        "attribute": "LIGHT",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2863439.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2863439.jpg"
    },
    {
        "id": "2906250",
        "name": "Grappler",
        "desc": "A devious snake with a thick body that wraps around an enemy monster and squeezes the life out of it.",
        "atk": "1300",
        "def": "1200",
        "type": "Normal Monster",
        "level": "4",
        "race": "Reptile",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/2906250.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/2906250.jpg"
    },
    {
        "id": "3134241",
        "name": "Flying Kamakiri 2",
        "desc": "A flying mantis that feeds primarily on insects.",
        "atk": "1500",
        "def": "800",
        "type": "Normal Monster",
        "level": "4",
        "race": "Insect",
        "attribute": "WIND",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/3134241.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/3134241.jpg"
    },
    {
        "id": "3170832",
        "name": "Takuhee",
        "desc": "This bird is known far and wide as a harbinger of doom.",
        "atk": "1450",
        "def": "1000",
        "type": "Normal Monster",
        "level": "4",
        "race": "Winged Beast",
        "attribute": "WIND",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/3170832.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/3170832.jpg"
    },
    {
        "id": "3606209",
        "name": "One Who Hunts Souls",
        "desc": "This dangerous creature brandishes a soul-sucking sword.",
        "atk": "1100",
        "def": "1000",
        "type": "Normal Monster",
        "level": "4",
        "race": "Beast-Warrior",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/3606209.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/3606209.jpg"
    },
    {
        "id": "4042268",
        "name": "Island Turtle",
        "desc": "A huge turtle that is often mistaken for an island.",
        "atk": "1100",
        "def": "2000",
        "type": "Normal Monster",
        "level": "4",
        "race": "Aqua",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/4042268.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/4042268.jpg"
    },
    {
        "id": "5053103",
        "name": "Battle Ox",
        "desc": "A monster with tremendous power, it destroys enemies with a swing of its axe.",
        "atk": "1700",
        "def": "1000",
        "type": "Normal Monster",
        "level": "4",
        "race": "Beast-Warrior",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/5053103.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/5053103.jpg"
    },
    {
        "id": "5265750",
        "name": "Skull Mariner",
        "desc": "A pirate ship that appears out of the mist and sinks any seagoing vessels.",
        "atk": "1600",
        "def": "900",
        "type": "Normal Monster",
        "level": "4",
        "race": "Warrior",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/5265750.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/5265750.jpg"
    },
    {
        "id": "6631034",
        "name": "Frostosaurus",
        "desc": "This monster's metabolism enables it to endure long periods of cold, harnessing the power to become a creature of solid ice! Nothing else can withstand such temperatures, especially victims of its glacial rampage.",
        "atk": "2600",
        "def": "1700",
        "type": "Normal Monster",
        "level": "6",
        "race": "Dinosaur",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/6631034.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/6631034.jpg"
    },
    {
        "id": "8353769",
        "name": "Air Eater",
        "desc": "A monster that feeds on oxygen, suffocating any who stand near.",
        "atk": "2100",
        "def": "1600",
        "type": "Normal Monster",
        "level": "6",
        "race": "Fiend",
        "attribute": "WIND",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/8353769.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/8353769.jpg"
    },
    {
        "id": "9540040",
        "name": "Boulder Tortoise",
        "desc": "A stone turtle that is nearly indestructible.",
        "atk": "1450",
        "def": "2200",
        "type": "Normal Monster",
        "level": "6",
        "race": "Aqua",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/9540040.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/9540040.jpg"
    },
    {
        "id": "11761845",
        "name": "Beast of Talwar",
        "desc": "Only the master of the sword among the Fiend-Type monsters is permitted to hold the Talwar.\n\n\n(This card is always treated as an \"Archfiend\" card.)",
        "atk": "2400",
        "def": "2150",
        "type": "Normal Monster",
        "level": "6",
        "race": "Fiend",
        "attribute": "DARK",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/11761845.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/11761845.jpg"
    },
    {
        "id": "13069066",
        "name": "Sword Arm of Dragon",
        "desc": "This Jurrasic juggernaut has a spine covered in sword-like plates, and a tail to split open skulls.",
        "atk": "1750",
        "def": "2030",
        "type": "Normal Monster",
        "level": "6",
        "race": "Dinosaur",
        "attribute": "EARTH",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/13069066.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/13069066.jpg"
    },
    {
        "id": "13140300",
        "name": "Hieratic Seal of the Sun Dragon Overlord",
        "desc": "A mysterious engraved Hieratic relic. It was thought to be a simple stone, but it was actually infused with the power of a sun-wielding dragon. Aeons passed, and the power of the relic grew and grew until it finally shone like the sun itself.",
        "atk": "0",
        "def": "0",
        "type": "Normal Monster",
        "level": "8",
        "race": "Dragon",
        "attribute": "LIGHT",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/13140300.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/13140300.jpg"
    },
    {
        "id": "32626733",
        "name": "Spiral Serpent",
        "desc": "When huge whirlpools lay cities asunder, it is the hunger of this sea serpent at work. No one has ever escaped its dreaded Spiral Wave to accurately describe the terror they experienced.",
        "atk": "2900",
        "def": "2900",
        "type": "Normal Monster",
        "level": "8",
        "race": "Sea Serpent",
        "attribute": "WATER",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/32626733.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/32626733.jpg"
    },
    {
        "id": "38999506",
        "name": "Cosmo Queen",
        "desc": "Queen of the galaxies and mistress of the stars.",
        "atk": "2900",
        "def": "2450",
        "type": "Normal Monster",
        "level": "8",
        "race": "Spellcaster",
        "attribute": "DARK",
        "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/38999506.jpg",
        "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/38999506.jpg"
    }

]